print('Введите первое число')
a = input()
print('Введите второе число')
b = input()
print (str(a), '+' ,str(b), '=' ,int(a)+int(b))
print (str(a), '-' ,str(b), '=' ,int(a)-int(b))
print (str(a), '*' ,str(b), '=' ,int(a)*int(b))